#define IDC_HOSTNAME                    1001
#define IDC_SOCKETNAME                  1002
#define IDC_BSIZE                       1003
#define IDC_ALL                         1008
#define IDC_OSIZE                       1009
#define IDC_OUTNAME                     1010
#define IDC_START                       1011
#define IDC_EXIT                        1012
#define IDC_EVENT		            	1013
#define IDC_STATUS                      1014
#define IDC_STOP                        1015
#define IDC_STATIC 			-1
#define IDC_EDIT3                       1006
#define IDC_EDIT4                       1007
#define IDC_EDIT5                       1008
#define IDC_EDIT6                       1009
#define IDC_MYHELP                      1020
