#include <windows.h>
#include <commdlg.h>
#include <commctrl.h>
#define IDR_TOOLBAR1 200
#define IDR_TOOLBAR2 201
#define ID_EXIT                     40001
#define ID_SELECT					40002
#define ID_REW						40003
#define ID_FORWARD					40004
#define ID_BACK						40005
#define ID_NEXT						40006
#define ID_PREV						40007
#define ID_COPY						40008
#define ID_STOP						50001
#define ID_TAPE						50002
#define ID_VERIFY					50003
#define ID_VIEW_HEADER				50004
#define IDC_EDIT1                       1002
#define IDC_DEVICE			1003
#define ID_PAUSE				50005
#define IDC_SOUR				1004
#define IDC_DEST				1005
#define ID_VIEW_HEX                     40009
#define ID_VIEW_ANSI                    40010
#define ID_VIEW_MASKA                   40013
#define ID_MASKA			50006
#define IDC_STATUS 50007
#define IDC_ODATA  50008
#define IDC_OEVENT 50009
#define IDC_CHN    50010
#define IDC_STATIC -1
#define ID_HELP                     50009
